export enum OrganizeAction {
  Pin = "pin",
  Unpin = "unpin",
  Mute = "mute",
  Unmute = "unmute",
  Snooze = "snooze",
  Unsnooze = "unsnooze",
  ChangeReminder = "changeReminder",
  ClearReminder = "clearReminder",
  SetAside = "setAside",
  Archive = "archive",
  MoveToInbox = "moveToInbox",
  MoveToTrash = "moveToTrash",
  MoveToFolder = "moveToFolder",
  AttachLabel = "attachLabel",
  DetachLabel = "detachLabel",
  MarkAsDone = "markAsDone",
  MarkAsUndone = "markAsUndone",
  MarkAsSeen = "markAsSeen",
  MarkAsUnseen = "markAsUnseen",
  MarkAsSpam = "markAsSpam",
  MarkThreadAsPriority = "markThreadAsPriority",
  UnmarkThreadAsPriority = "unmarkThreadAsPriority",
  Unsubscribe = "unsubscribe",
  ChangeCategoryPersonal = "changeCategoryPersonal",
  ChangeCategoryNotification = "changeCategoryNotification",
  ChangeCategoryNewsletters = "changeCategoryNewsletters",
  ShareInTeam = "shareInTeam",
  Assign = "assign",
  DelegationComplete = "delegationComplete",
  DelegationReopen = "delegationReopen",
}

/** Actions that modify emails — all require Triage access (Pro plan) via Spark CLI */
export const TRIAGE_ACTIONS = new Set<OrganizeAction>([
  OrganizeAction.Pin,
  OrganizeAction.Unpin,
  OrganizeAction.Mute,
  OrganizeAction.Unmute,
  OrganizeAction.Snooze,
  OrganizeAction.Unsnooze,
  OrganizeAction.ChangeReminder,
  OrganizeAction.ClearReminder,
  OrganizeAction.SetAside,
  OrganizeAction.Archive,
  OrganizeAction.MoveToInbox,
  OrganizeAction.MoveToTrash,
  OrganizeAction.MoveToFolder,
  OrganizeAction.AttachLabel,
  OrganizeAction.DetachLabel,
  OrganizeAction.MarkAsDone,
  OrganizeAction.MarkAsUndone,
  OrganizeAction.MarkAsSeen,
  OrganizeAction.MarkAsUnseen,
  OrganizeAction.MarkAsSpam,
  OrganizeAction.MarkThreadAsPriority,
  OrganizeAction.UnmarkThreadAsPriority,
  OrganizeAction.Unsubscribe,
  OrganizeAction.ChangeCategoryPersonal,
  OrganizeAction.ChangeCategoryNotification,
  OrganizeAction.ChangeCategoryNewsletters,
  OrganizeAction.ShareInTeam,
  OrganizeAction.Assign,
  OrganizeAction.DelegationComplete,
  OrganizeAction.DelegationReopen,
]);
